services:
  db:
    image: "postgres:16"
    volumes:
      - pg-data:/var/lib/postgresql/data
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - 5432:5432

volumes:
  pg-data:
